//10-5- Search Engine Optimization


import AuthProvider from "./auth/Provider";

import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";

import NavBar from "./NavBar";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";


import localFont from "next/font/local"

const inter = Inter({ subsets: ["latin"] });


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"]
})


const poppins = localFont({
  src: "../public/fonts/Poppins-Black.ttf",
  variable: "--font-poppins"
})


//1-This "metadata" was part of "the starter code" so we didn't write it 
//earlier.Now, whenever we export a "metadata object" from a layout or 
//a page file, Next.js will automatically "include that metadata object
//in the head of our HTML" And as you probably know, "search engines" 
//look for these metatags to index our content.
//So to make our websites search engine friendly, we should make sure 
//that every page has "proper metatags".
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   openGraph: {//2-This is used when we "share our pages on social media 
//     //platforms".At a minimum, we should provide a "title" and a 
//     //"description".There are other properties like images, 
//     //category and so on.
//     //
//     title: "...",
//     description: "..."
//   }

// };
//3-So with this metadata object in our root layout, every page will
//have these metatags.And then we can go to individual pages and 
//overwrite these values.
//Go to home page , page.tsx .

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />

      <body className={poppins.className}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}



