//8-7-Signing Out users

"use client";

import Link from "next/link";
import React from "react";

import { useSession } from "next-auth/react";

const NavBar = () => {
  const { status, data: session } = useSession();

  return (
    <div className="flex justify-between text-cyan-50 bg-slate-500 p-5">
      <div>
        <Link href="/">Next.js</Link>
      </div>
      <ul className="flex justify-around gap-3">
        <li>
          <Link href="/users">Users</Link>
        </li>
        <li>
          <Link href="/products">Products</Link>
        </li>
        {status === "loading" && <li>Loading ...</li>}
        {status === "authenticated" && (
          <li>
            {session.user!.name}
            {/*1-we can add a link here for sign out.this is another end 
            point that is handled by next auth. */}
            <Link href="/api/auth/signout" className="ml-2">
              Sign Out
            </Link>
            {/*2-When we click on the sign out button, a page generated by
              next auth.if you don't like the way this page or the signing
               page looks, you can always customize it. */}
          </li>
        )}
        {status === "unauthenticated" && (
          <li>
            <Link href="/api/auth/signin">Login</Link>
          </li>
        )}
      </ul>
    </div>
  );
};

export default NavBar;
